#!/usr/bin/env python
import sys
from pyppl import config_plugins
import pyppl_require
config_plugins(pyppl_require)
from pyppl import console

if len(sys.argv) > 1 and sys.argv[1] != 'require':
	raise RuntimeError('This is only for pyppl_require test, please pass the subcommand "require" to me!')

console.main()
